PRAGMA foreign_keys = ON;
PRAGMA encoding = "UTF-8";

CREATE TABLE IF NOT EXISTS userdata(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
password TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS item(
id INTEGER PRIMARY KEY AUTOINCREMENT,
itemname TEXT NOT NULL,
targetnum INTEGER DEFAULT 0 NOT NULL,
finishednum INTEGER DEFAULT 0 NOT NULL,
path TEXT NOT NULL);